abstract: add extra stashes of data to your objects
author: Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Mixin-ExtraFields
no_index: 
  directory: 
    - inc
    - t
requires: 
  Sub::Exporter: 0.972
version: 0.003
