--- 
abstract: add extra stashes of data to your objects
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Mixin-ExtraFields
no_index: 
  directory: 
    - inc
    - t
version: 0.006
